'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { addDoc, collection, doc, onSnapshot, orderBy, query, serverTimestamp, updateDoc } from 'firebase/firestore';
import { CalendarClock, CheckCircle2, Mail, MapPin, Pencil, Phone, Plus, Users, X } from 'lucide-react';
import { db } from '@/lib/firebase';

type Option = { id: string; name?: string; company?: string; email?: string };
type ActionType = 'call' | 'visit' | 'email' | 'meeting' | 'task' | 'other';
type CommercialAction = { id: string; title: string; type: ActionType; status: 'pending' | 'in_progress' | 'done' | 'cancelled'; dueDate?: string; companyId?: string; contactId?: string; opportunityId?: string; detail?: string };
const emptyForm = { title: '', type: 'call' as ActionType, status: 'pending' as CommercialAction['status'], dueDate: '', companyId: '', contactId: '', opportunityId: '', detail: '' };
const types: Array<{ value: ActionType; label: string }> = [{ value: 'call', label: 'Llamada telefónica' }, { value: 'visit', label: 'Visita' }, { value: 'email', label: 'Email' }, { value: 'meeting', label: 'Reunión' }, { value: 'task', label: 'Tarea' }, { value: 'other', label: 'Otra' }];

export default function CrmActions() {
  const [actions, setActions] = useState<CommercialAction[]>([]);
  const [companies, setCompanies] = useState<Option[]>([]);
  const [contacts, setContacts] = useState<Option[]>([]);
  const [opportunities, setOpportunities] = useState<Option[]>([]);
  const [form, setForm] = useState(emptyForm);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [open, setOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [filter, setFilter] = useState<'all' | CommercialAction['status']>('all');
  const [error, setError] = useState('');

  useEffect(() => {
    const stops = [
      onSnapshot(query(collection(db, 'crmActions'), orderBy('createdAt', 'desc')), (snapshot) => setActions(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as CommercialAction))), (err) => setError(err.message)),
      onSnapshot(collection(db, 'crmCompanies'), (snapshot) => setCompanies(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as Option)))),
      onSnapshot(collection(db, 'crmContacts'), (snapshot) => setContacts(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as Option)))),
      onSnapshot(collection(db, 'contactRequests'), (snapshot) => setOpportunities(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as Option)))),
    ];
    return () => stops.forEach((stop) => stop());
  }, []);

  const visible = useMemo(() => actions.filter((action) => filter === 'all' || action.status === filter), [actions, filter]);
  const close = () => { setOpen(false); setEditingId(null); setForm(emptyForm); };
  const edit = (action: CommercialAction) => { setEditingId(action.id); setForm({ title: action.title, type: action.type, status: action.status, dueDate: action.dueDate ?? '', companyId: action.companyId ?? '', contactId: action.contactId ?? '', opportunityId: action.opportunityId ?? '', detail: action.detail ?? '' }); setOpen(true); };
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const payload = { ...form, updatedAt: serverTimestamp() }; if (editingId) await updateDoc(doc(db, 'crmActions', editingId), payload); else await addDoc(collection(db, 'crmActions'), { ...payload, createdAt: serverTimestamp() }); close(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : 'No se pudo guardar.'); } finally { setSaving(false); } };

  const typeIcon = (type: ActionType) => type === 'call' ? Phone : type === 'visit' ? MapPin : type === 'email' ? Mail : type === 'meeting' ? Users : CheckCircle2;
  const relatedLabel = (action: CommercialAction) => companies.find((item) => item.id === action.companyId)?.name || contacts.find((item) => item.id === action.contactId)?.name || opportunities.find((item) => item.id === action.opportunityId)?.company || opportunities.find((item) => item.id === action.opportunityId)?.name || 'Sin vinculación';

  return <div><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow">Seguimiento comercial</p><h1 className="mt-2 text-3xl font-extrabold">Acciones</h1><p className="mt-2 text-sm text-late4-slate">Llamadas, visitas, emails, reuniones y próximos pasos.</p></div><button className="btn-primary gap-2" onClick={() => setOpen(true)}><Plus size={17} /> Nueva acción</button></div>
    {error && <p className="mt-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}
    <section className="mt-7 overflow-hidden rounded-xl border border-late4-ink/5 bg-white shadow-sm"><div className="flex justify-end border-b border-late4-ink/5 p-4"><select className="rounded-lg border border-late4-ink/10 bg-white px-3 py-2 text-sm font-bold" value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)}><option value="all">Todos los estados</option><option value="pending">Pendientes</option><option value="in_progress">En curso</option><option value="done">Hechas</option><option value="cancelled">Canceladas</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-late4-paper/70 text-[11px] uppercase tracking-wider text-late4-slate"><tr><th className="px-5 py-3">Acción</th><th className="px-5 py-3">Vinculada a</th><th className="px-5 py-3">Estado</th><th className="px-5 py-3">Fecha</th><th className="px-5 py-3">Detalle</th><th className="px-5 py-3 text-right">Acción</th></tr></thead><tbody className="divide-y divide-late4-ink/5">{visible.map((action) => { const Icon = typeIcon(action.type); return <tr key={action.id}><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-late4-teal-soft text-late4-teal"><Icon size={16} /></div><div><p className="font-extrabold">{action.title}</p><p className="text-xs text-late4-slate">{types.find((item) => item.value === action.type)?.label}</p></div></div></td><td className="px-5 py-4 font-bold text-late4-teal">{relatedLabel(action)}</td><td className="px-5 py-4">{action.status === 'done' ? 'Hecha' : action.status === 'in_progress' ? 'En curso' : action.status === 'cancelled' ? 'Cancelada' : 'Pendiente'}</td><td className="px-5 py-4">{action.dueDate ? <span className="inline-flex items-center gap-1.5"><CalendarClock size={14} />{action.dueDate}</span> : '—'}</td><td className="max-w-xs truncate px-5 py-4 text-late4-slate">{action.detail || '—'}</td><td className="px-5 py-4 text-right"><button className="grid h-9 w-9 place-items-center rounded-lg bg-late4-paper text-late4-slate" onClick={() => edit(action)}><Pencil size={15} /></button></td></tr>; })}{!visible.length && <tr><td className="px-5 py-10 text-center text-late4-slate" colSpan={6}>No hay acciones para este filtro.</td></tr>}</tbody></table></div></section>
    {open && <div className="fixed inset-0 z-50 grid place-items-center bg-late4-ink/60 p-4 backdrop-blur-sm"><section className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b border-late4-ink/10 px-6 py-5"><div><p className="eyebrow">CRM</p><h2 className="mt-1 text-2xl font-extrabold">{editingId ? 'Editar acción' : 'Nueva acción'}</h2></div><button className="grid h-9 w-9 place-items-center rounded-lg bg-late4-paper" onClick={close}><X size={17} /></button></header><form className="p-6" onSubmit={save}><div className="grid gap-4 md:grid-cols-2"><Field label="Título *"><input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></Field><Field label="Tipo"><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value as ActionType })}>{types.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></Field><Field label="Estado"><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as CommercialAction['status'] })}><option value="pending">Pendiente</option><option value="in_progress">En curso</option><option value="done">Hecha</option><option value="cancelled">Cancelada</option></select></Field><Field label="Fecha"><input type="date" value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} /></Field><Field label="Empresa"><select value={form.companyId} onChange={(event) => setForm({ ...form, companyId: event.target.value })}><option value="">Sin empresa</option>{companies.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Contacto"><select value={form.contactId} onChange={(event) => setForm({ ...form, contactId: event.target.value })}><option value="">Sin contacto</option>{contacts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field className="md:col-span-2" label="Oportunidad"><select value={form.opportunityId} onChange={(event) => setForm({ ...form, opportunityId: event.target.value })}><option value="">Sin oportunidad</option>{opportunities.map((item) => <option key={item.id} value={item.id}>{item.company || item.name || item.email}</option>)}</select></Field><Field className="md:col-span-2" label="Detalle"><textarea rows={3} value={form.detail} onChange={(event) => setForm({ ...form, detail: event.target.value })} /></Field></div><div className="mt-6 flex justify-end gap-3 border-t border-late4-ink/10 pt-5"><button className="btn-secondary" onClick={close} type="button">Cancelar</button><button className="btn-primary" disabled={saving} type="submit">{saving ? 'Guardando…' : 'Guardar acción'}</button></div></form></section></div>}
  </div>;
}

function Field({ label, className = '', children }: { label: string; className?: string; children: React.ReactNode }) { return <label className={`block text-sm font-bold ${className}`}><span>{label}</span><div className="mt-2 [&>input]:w-full [&>input]:rounded-lg [&>input]:border [&>input]:border-late4-ink/15 [&>input]:px-3 [&>input]:py-2.5 [&>input]:font-normal [&>select]:w-full [&>select]:rounded-lg [&>select]:border [&>select]:border-late4-ink/15 [&>select]:bg-white [&>select]:px-3 [&>select]:py-2.5 [&>select]:font-normal [&>textarea]:w-full [&>textarea]:rounded-lg [&>textarea]:border [&>textarea]:border-late4-ink/15 [&>textarea]:px-3 [&>textarea]:py-2.5 [&>textarea]:font-normal">{children}</div></label>; }
